---
title: "Ejemplo 2"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(plotly)
base=read.csv("manzanas.csv", sep = ";")
base$trat=as.factor(base$trat)
```

Column
-----------------------------------------------------------------------

### Chart A

```{r}
p <- ggplot(base, aes(x=color, y=trat)) +
            geom_point(shape=1)      
ggplotly(p)
```


Column {.tabset }
-----------------------------------------------------------------------

### Chart B

```{r}
n <- 20
x1 <- rnorm(n); x2 <- rnorm(n)
y1 <- 2 * x1 + rnorm(n)
y2 <- 3 * x2 + (2 + rnorm(n))
A <- as.factor(rep(c(1, 2), each = n))
df <- data.frame(x = c(x1, x2), y = c(y1, y2), A = A)
fm <- lm(y ~ x + A, data = df)

p <- ggplot(data = cbind(df, pred = predict(fm)), aes(x = x, y = y, color = A))
p <- p + geom_point() + geom_line(aes(y = pred))
ggplotly(p)

```

### Chart C

```{r}
p1 <- ggplot(base, aes(x=juez, y=color)) +
            geom_point(shape=2)      
ggplotly(p1)

```



